# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cec03aa0eebb67523611e52dc490e5a8310a82b2fa636c063d5fe99013f08c58abcdd3e1e29803133b9d61c889028d133718bc2568902c2a07c035202d0c188

test:
  secret_key_base: 334aa2bd8b8a491cfb3dadcc127ecf7f3b5f2980ec07c2e64793891a771a63e22ec9de47d94ad1b2b4ead6d51d2bdf766f648861953109a4ddde102b7d25f68e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
